app = "sms-bulk-render"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "performance-16x"
  memory = "39gb"
  cpu_kind = "performance"
  cpus = 12
  processes = ["app"]
